spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?seUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 3
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
    refresh: true
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-enums-package: com.example.demo.multi.springBoot.mybatisPlus.enums
  type-aliases-package: com.example.demo.multi.springBoot.mybatisPlus.entity
  type-aliases-super-type: com.baomidou.mybatisplus.extension.activerecord.Model
  configuration:
    call-setters-on-nulls: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: warning
