dubbo:
  application:
    name: demo-multi-spring-boot
    owner: abc
    organization: abc
  scan:
    base-packages: com.example.demo.multi.springBoot
  registry:
    id: regi-center-id
    protocol: zookeeper
  protocol:
    name: dubbo-consumer
    timeout: 3000
  monitor:
    protocol: registry


spring:
  messages:
    basename: i18n/messages
logging:
  level:
    org:
      apache:
        dubbo:
          common: error
      springframework:
        boot:
          autoconfigure: error