spring:
 datasource:
       username: root
       password: 3
       url: jdbc:mysql://localhost:3306/lottery?serverTimezone=GMT
       driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**Mapper.xml


#logging:
#  level:
#    com:
#      example:
#        demo:
#          multi:
#            springBoot:
#              mapper: debug