dubbo:
  config-center:
    address: zookeeper://192.168.240.15:2181
  registry:
    address: 192.168.240.15:2181
  protocol:
    port: 20880

server:
  port: 8100
spring:
  http:
    log-request-details: true
  redis:
    host: 192.168.3.128
    port: 6379
    database: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisPlus?seUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 3

logging:
  config: classpath:log4j2-dev.yml

mybatis-plus:
  delay-seconds: 10
  sleep-seconds: 10



