spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_springboot?seUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 3
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-enums-package: com.example.demo.multi.springBoot.mybatisPlus.enums
logging:
  level:
    root: warning
