dubbo:
  application:
    name: demo-multi-spring-boot
    owner: abc
    organization: abc
  scan:
    base-packages: com.example.demo.multi.springBoot
  registry:
    id: regi-center-id
    protocol: zookeeper
  protocol:
    name: dubbo-consumer
    timeout: 3000
  monitor:
    protocol: registry


spring:
  messages:
    basename: i18n/messages
logging:
  level:
    org:
      apache:
        dubbo:
          common: error
      springframework:
        boot:
          autoconfigure: error
mybatis-plus:
  mapper-locations: com.example.demo.multi.springBoot.dao.**.*Mapper.xml
  type-aliases-package: com.example.demo.multi.springBoot.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  type-enums-package: com.example.demo.multi.springBoot.constant.Enum