CREATE TABLE `user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `age` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `del_flag` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`id`)
)
  COLLATE='utf8mb4_general_ci'
  ENGINE=InnoDB
  AUTO_INCREMENT=6
;
